remote_theme: just-the-docs/just-the-docs
title: TFE2 Modding
color_scheme: dark
aux_links:
  "Official Modding Guide":
    - "https://florianvanstrien.nl/TheFinalEarth2/modding.php"
# External navigation links
nav_external_links:
  - title: Official Modding Guide
    url: https://florianvanstrien.nl/TheFinalEarth2/modding.php

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/DT-is-not-available/tfe2-modding"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"

callouts:
  danger:
    title: Warning
    color: red
  warning:
    title: Warning
    color: yellow
  info:
    title: Info
    color: blue
